# Generated by Django 5.1 on 2024-08-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactado',
            field=models.BooleanField(default=False, verbose_name='Ya me contacté'),
        ),
    ]
