# Generated by Django 5.1 on 2024-08-11 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
