# Generated by Django 5.1 on 2024-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la home'),
        ),
    ]
