# Generated by Django 5.1 on 2024-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_images',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='Portada del curso'),
        ),
    ]
